name: Telegram RSS Bot

on:

  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py

      - name: Commit updated last_news.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add last_news.txt

          git diff --cached --quiet || git commit -m "Update last news"

          git push

      - name: Telegram alert on failure
        if: failure()

        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.ALERT_CHAT_ID }} \
          -d text="⚠️ ERRORE BOT Telegram Azienda Speciale%0AWorkflow GitHub Actions fallito"